create or replace TABLE ETL_DB.TARGET_SCHEMA.D_TGT_ORDER (
	ORDER_ID NUMBER(10,0),
	FIRST_NAME VARCHAR(10),
	CUST_ID NUMBER(10,0),
	ORDER_AMOUNT NUMBER(12,2),
	EFFECTIVE_DATE DATE,
	END_DATE DATE,
	CUST_KEY NUMBER(10,0)
);
