create or replace TABLE ETL_DB.TARGET_SCHEMA.D_TGT_CUSTOMER (
	CUST_ID NUMBER(10,0) NOT NULL,
	FIRST_NAME VARCHAR(10),
	LAST_NAME VARCHAR(10),
	EMAIL VARCHAR(20),
	PHONE NUMBER(10,0),
	ADDRESS VARCHAR(15),
	CITY VARCHAR(10),
	STATE VARCHAR(10),
	COUNTRY VARCHAR(10),
	ACTIVE_STATUS VARCHAR(1),
	CUST_KEY NUMBER(10,0),
	primary key (CUST_ID)
);
