create or replace TABLE ETL_DB.SOURCE_SCHEMA.D_SRC_CUSTOMER (
	CUST_ID NUMBER(10,0) NOT NULL,
	FIRST_NAME VARCHAR(10) NOT NULL,
	LAST_NAME VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(30),
	PHONE NUMBER(10,0),
	ADDRESS VARCHAR(15),
	CITY VARCHAR(10),
	STATE VARCHAR(10),
	COUNTRY VARCHAR(10),
	unique (EMAIL),
	primary key (CUST_ID)
);
