create or replace TABLE ETL_DB.SOURCE_SCHEMA.D_SRC_EMP (
	EMP_ID NUMBER(10,0) NOT NULL,
	FIRST_NAME VARCHAR(16777216) NOT NULL,
	LAST_NAME VARCHAR(16777216) NOT NULL,
	EMAIL VARCHAR(16777216),
	SALARY NUMBER(10,2),
	HIRE_DATE DATE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	primary key (EMP_ID)
);
